engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "phpcs.ruleset.xml"
      ignore_warnings: true
    checks:
      Squiz Commenting InlineComment InvalidEndChar:
        enabled: false
      Squiz Commenting InlineComment SpacingBefore:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
- bin/
- vendor/
